# - docs: https://alacritty.org/config-alacritty.html

live_config_reload = true

import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/fonts.toml",
]

[bell]
animation = "EaseOutExpo"
duration = 0

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "Transparent"
dynamic_title = true
startup_mode = "Maximized"
option_as_alt = "Both"
opacity = 0.9

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4


