#!/bin/zsh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" > /tmp/homebrew-install.log
fi

# The set of packages I want installed by default
packages=(
  # Install GNU core utilities (those that come with OS X are outdated)
  coreutils

  # Uncomment to install Bash; default on mac is zsh
  # bash
  # bash-completion

  # Install everything else
  git

  # htop is an interactive process viewer for Unix systems
  # https://htop.dev/
  htop
  node

  # grc is a terminal colorizer utility
  # https://kassiopeia.juls.savba.sk/~garabik/software/grc.html
  grc
)

# Set of Casks (GUI apps) I want installed by default
declare -A casks
casks=(
  iterm2 "iTerm.app"

  # Amethyst is a tiling window manager for macOS
  # https://github.com/ianyh/Amethyst
  amethyst "Amethyst.app"

  # MonitorControl is a macOS app to control external monitors brightness & volume
  monitorcontrol "MonitorControl.app"

  # Developer Tools
  sublime-text "Sublime Text.app"
  github "GitHub Desktop.app"
  jetbrains-toolbox "JetBrains Toolbox.app"

  spotify "Spotify.app"
)

# Make sure we’re using the latest Homebrew
info "updating Homebrew"
brew update >/dev/null 2>/dev/null
success "Homebrew is up to date"

# Upgrade any already-installed formulae
info "upgrade installed formulae"
brew upgrade >/dev/null 2>/dev/null
success "Formulae are all up to date"

for i in "${packages[@]}"
do
  info "installing $i"
  CMD="brew install $i"
  $CMD >/dev/null 2>/dev/null
  success "$i is now installed"
done

for key value in ${(kv)casks}
do
  info "installing $key"

  # Exit silently if the app is already installed
  if [ -d "$value" ]
  then
    continue 0
  fi

  CMD="brew install --cask $i"
  $CMD >/dev/null 2>/dev/null
  success "$i is now installed"
done

# Remove outdated versions from the cellar
brew cleanup >/dev/null 2>/dev/null

exit 0
